version: "3.2"
services:
  packager:
    image: nytimes/nginx-vod-module:v1.3.1
    ports:
      - 1988:80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /usr/local/nginx/conf/nginx.conf
    depends_on:
      - gcs_helper
  gcs_helper:
    image: nytimes/gcs-helper:v3.2.2
    env_file:
      - gcs_helper.env
    volumes:
      - $HOME/.config/gcloud/application_default_credentials.json:/etc/google-creds.json
